name: Generate Binary for Windows

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: ðŸ˜€ build Binary
      run: cargo build --release
    - name: ðŸŽ‰ save Binary
      uses: actions/upload-artifact@v3
      with:
          name: release
          path: ./target/release/Impuls_ao_Creator.exe
    - name: ðŸ“„ add to Release
      uses: softprops/action-gh-release@v1
      with:
          files: ./target/release/Impuls_ao_Creator.exe
